### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GangGamerAK** [TimboKZ/discord-spoiler-bot#20]
```npm
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\GangGamerAK\Pictures\Botspoiler\node_modules\canvas\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\GangGamerAK\Pictures\Botspoiler\node_modules\canvas
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN discord.js@11.2.1 requires a peer of bufferutil@^3.0.2 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of erlpack@hammerandchisel/erlpack but none was installed.
npm WARN discord.js@11.2.1 requires a peer of node-opus@^0.2.6 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of opusscript@^0.0.3 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of sodium@^2.0.1 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of libsodium-wrappers@^0.5.4 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of uws@^0.14.5 but none was installed.
npm WARN botspoiler@1.0.0 No description
npm WARN botspoiler@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GangGamerAK\AppData\Roaming\npm-cache\_logs\2017-10-11T17_14_25_266Z-debug.log
```

I am having this error help please

**Comment by TimboKZ** [comment]
Looks like you're missing some `node-canvas` prerequisites. Check the [Installation section](https://github.com/TimboKZ/discord-spoiler-bot/wiki/Installation) in the wiki, it will have the link to `node-canvas` repository with further instructions.

**Comment by TimboKZ** [comment]
Assuming this was resolved, closing the issue.
